version: '2.0'
services:
  frontend:
    image: myappfrontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 8081:3000
  backend:
    image: myappbackend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080